name: cruzhacks-2023-live-site-development

env:
  VITE_REACT_APP_TITLE: ${{ secrets.VITE_REACT_APP_TITLE }}
  VITE_AUTH0_DOMAIN: ${{ secrets.VITE_AUTH0_DOMAIN }}
  VITE_AUTH0_CLIENTID: ${{ secrets.VITE_AUTH0_CLIENTID }}
  VITE_AUTH0_AUDIENCE: ${{ secrets.VITE_AUTH0_AUDIENCE }}
  VITE_FIREBASE_CONFIG: ${{ secrets.VITE_FIREBASE_CONFIG_DEV }}
  
on:
  push:
    branches: [development]
  pull_request:
    branches: [development, feature/**]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Create Production Build
        run: yarn build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Lint Typescript
        run: yarn lint:ts

  auto-deploy-to-test:
    runs-on: ubuntu-latest
    needs: [build, lint]
    if: github.ref == 'refs/heads/development'
    steps:
      - uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Deploy to Firebase -- Test
        run: yarn deploy:dev --token $token
        env:
          token: ${{ secrets.FIREBASE_TOKEN }}
